version: "3"

services:
  consul:
    image: consul
    command: agent -server -bootstrap -ui
    hostname: consul-1
    environment:
      - CONSUL_BIND_INTERFACE=eth0
      - CONSUL_CLIENT_INTERFACE=eth0

  nginx:
    image: gluufederation/nginx:3.1.2_dev
    hostname: singlehost.gluu.local
    environment:
      - GLUU_KV_HOST=consul
      - GLUU_OXAUTH_BACKEND=oxauth:8080
      - GLUU_OXTRUST_BACKEND=oxtrust:8080

  ldap:
    image: gluufederation/openldap:3.1.2_dev
    environment:
      - GLUU_KV_HOST=consul
      - GLUU_LDAP_INIT=true
      - GLUU_LDAP_INIT_HOST=singlehost_ldap_1
      - GLUU_LDAP_INIT_PORT=1636

  oxauth:
    image: gluufederation/oxauth:3.1.2_dev
    environment:
      - GLUU_KV_HOST=consul
      - GLUU_LDAP_URL=ldap:1636

  oxtrust:
    image: gluufederation/oxtrust:3.1.2_dev
    environment:
      - GLUU_KV_HOST=consul
      - GLUU_LDAP_URL=ldap:1636
    extra_hosts:
      # TODO: dont hardcode
      - "singlehost.gluu.local:172.19.0.3"
